name: Daily update

on:
  workflow_dispatch:
  schedule:
    # UTC+8 0600
    - cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
      - name: Scraping
        run: |
          cd tools && go run . && mv animad.json ../src/data/ && mv bilibili.json ../src/data/ && mv update.json ../src/data/ && cd ..
          git config --global user.name 'Js0n'
          git config --global user.email '29531167+JasonKhew96@users.noreply.github.com'
          git commit -am "Automated update"
          git push
